services:

  nuxt:
    image: ghcr.io/kevindebenedetti/portfolio:latest
    pull_policy: always
    restart: always
    expose:
      - 3000
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.portfolio-nuxt.rule=Host(`kevindb.dev`, `www.kevindb.dev`)
      - traefik.http.routers.portfolio-nuxt.entrypoints=websecure
      - traefik.http.routers.portfolio-nuxt.tls.certResolver=letsencrypt
      - traefik.http.services.portfolio-nuxt.loadbalancer.server.port=3000

      # Redirection www vers non-www
      - traefik.http.middlewares.redirect-regex.redirectregex.regex=^https://www\\.kevindb\\.dev/(.*)
      - traefik.http.middlewares.redirect-regex.redirectregex.replacement=https://kevindb.dev/$${1}
      - traefik.http.middlewares.redirect-regex.redirectregex.permanent=true
      - traefik.http.routers.portfolio-nuxt.middlewares=redirect-regex
      
networks:
  dokploy-network:
    external: true