services:

  nuxt:
    image: ghcr.io/kevindebenedetti/portfolio:latest
    pull_policy: always
    restart: always
    expose:
      - 3000
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.nuxt-app.rule=Host(`kevindb.dev`)
      - traefik.http.routers.nuxt-app.entrypoints=web
      - traefik.http.services.nuxt-app.loadbalancer.server.port=3000

networks:
  dokploy-network:
    external: true