services:

  nuxt:
    image: ghcr.io/kevindebenedetti/portfolio:latest
    pull_policy: always
    restart: always
    expose:
      - 3000
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      # DÃ©finition explicite du service
      - traefik.http.services.portfolio.loadbalancer.server.port=3000

      # Configuration du routeur principal
      - traefik.http.routers.portfolio.rule=Host(`kevindb.dev`, `www.kevindb.dev`)
      - traefik.http.routers.portfolio.entrypoints=websecure
      - traefik.http.routers.portfolio.tls.certResolver=letsencrypt
      - traefik.http.routers.portfolio.service=portfolio

      # Redirection www vers non-www
      - traefik.http.middlewares.redirect-regex.redirectregex.regex=^https://www\\.kevindb\\.dev/(.*)
      - traefik.http.middlewares.redirect-regex.redirectregex.replacement=https://kevindb.dev/$${1}
      - traefik.http.middlewares.redirect-regex.redirectregex.permanent=true
      - traefik.http.routers.portfolio.middlewares=redirect-regex

networks:
  dokploy-network:
    external: true