services:

  nuxt:
    image: ghcr.io/kevindebenedetti/portfolio:latest
    pull_policy: always
    restart: always
    expose:
      - 3000
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.portfolio-nuxt.rule=Host(`kevindb.dev`)
      - traefik.http.routers.portfolio-nuxt.entrypoints=websecure
      - traefik.http.routers.portfolio-nuxt.tls.certResolver=letsencrypt
      - traefik.http.services.portfolio-nuxt.loadbalancer.server.port=3000

      - traefik.http.routers.redirect-www.rule=Host(`www.kevindb.dev`)
      - traefik.http.routers.redirect-www.entrypoints=web
      - traefik.http.routers.redirect-www.middlewares=redirect-to-non-www
      - traefik.http.middlewares.redirect-to-non-www.redirectregex.regex=^https://www\.(.*)
      - traefik.http.middlewares.redirect-to-non-www.redirectregex.replacement=https://$1
      - traefik.http.middlewares.redirect-to-non-www.redirectregex.permanent=true

networks:
  dokploy-network:
    external: true