name: Versions

on:
  workflow_call:

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      node-version: ${{ steps.set.outputs.node-version }}
    steps:
      - name: Set versions
        id: set
        run: |
          echo "node-version=22.20.0" >> $GITHUB_OUTPUT
      - name: Output versions
        run: |
          echo "Node: ${{ steps.set.outputs.node-version }}"
